version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo_network

  mongodb2:
    image: mongo:latest
    container_name: mongodb2
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data2:/data/db
    networks:
      - mongo_network

  mongodb3:
    image: mongo:latest
    container_name: mongodb3
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data3:/data/db
    networks:
      - mongo_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb
    networks:
      - mongo_network

  python-app:
    build: .
    container_name: python-app
    depends_on:
      - mongodb
    networks:
      - mongo_network

  pizzas_menu_api:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - mongodb2
    networks:
      - mongo_network

  pizzas_customers_api:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - mongodb3
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_data2:
    driver: local
  mongodb_data3:
    driver: local